export const paths = {
  support: '/support',
  verifyCertificate: '/verify',
  auth: {
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
  },
  onboarding: {
    student: '/onboarding/student',
    teacher: '/onboarding/teacher',
  },
  student: {
    dashboard: '/student/dashboard',
    courses: '/student/courses',
    aiTutor: '/student/ai-tutor',
    assignmentHelper: '/student/assignment-helper',
    gpa: '/student/gpa',
    certificates: '/student/certificates',
    examPrep: '/student/exam-prep',
    examHistory: '/student/exam-history',
    community: '/student/community',
    settings: '/student/settings',
    notifications: '/student/notifications',
  },
  teacher: {
    dashboard: '/teacher/dashboard',
    courses: '/teacher/courses',
    coursesNew: '/teacher/courses/new',
    courseDetails: '/teacher/courses/:courseId',
    students: '/teacher/students',
    analytics: '/teacher/analytics',
    resources: '/teacher/resources',
    community: '/teacher/community',
    settings: '/teacher/settings',
    notifications: '/teacher/notifications',
    earnings: '/teacher/earnings',
    pending: '/teacher/pending',
  },
  admin: {
    login: '/admin/login',
    dashboard: '/admin/dashboard',
    users: '/admin/users',
    moderation: '/admin/moderation',
    support: '/admin/support',
    coursesNew: '/admin/courses/new',
    courseDetails: '/admin/moderation/courses/:courseId',
    financials: '/admin/financials',
    generator: '/admin/generator',
    settings: '/admin/settings',
  }
} as const;
